#ifndef LEASTSQUAREREGRESSIONLIBRARY_GLOBAL_H
#define LEASTSQUAREREGRESSIONLIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LEASTSQUAREREGRESSIONLIBRARY_LIBRARY)
#  define LEASTSQUAREREGRESSIONLIBRARYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LEASTSQUAREREGRESSIONLIBRARYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LEASTSQUAREREGRESSIONLIBRARY_GLOBAL_H
